# Generated by Django 3.2.5 on 2023-04-28 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^\\d{1,10}$')])),
                ('Profile', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('Github', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Linkedin', models.CharField(max_length=100)),
            ],
        ),
    ]
