# Generated by Django 3.2.5 on 2023-04-28 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='phone',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Address',
            field=models.CharField(default='Delhi', max_length=100),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Phone',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Only digits are allowed', regex='^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.tech', 'M.tech'), ('M.Sc', 'M.Sc'), ('P.hd', 'P.hd'), ('M.S.R.', 'M.S.R.'), ('Senior Secondary', 'Senior Secondary'), ('Secondary', 'Secondary')], default='B.Tech', max_length=30)),
                ('Field', models.CharField(max_length=100)),
                ('Institute', models.CharField(max_length=100)),
                ('CGPA', models.FloatField()),
                ('Start', models.DateField()),
                ('End', models.DateField()),
                ('Resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.resume')),
            ],
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Resume.resume'),
        ),
    ]
