# Generated by Django 3.2.5 on 2023-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Start', models.DateField()),
                ('End', models.DateField()),
                ('Description', models.TextField()),
                ('code', models.URLField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
