# Generated by Django 3.2.5 on 2023-04-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Resume.resume'),
        ),
    ]
