# Generated by Django 3.2.5 on 2023-04-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0008_achievements_certifications_extracurricular_pors_professionalsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Resume.resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Resume.resume'),
        ),
    ]
