# Generated by Django 3.2.5 on 2023-04-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0009_auto_20230428_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='Github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='Linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='Website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
