# Generated by Django 3.2.5 on 2023-04-29 08:15

import Resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0010_auto_20230429_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalsummary',
            name='Summary',
            field=models.TextField(validators=[Resume.models.validate_summary_length]),
        ),
    ]
