# Generated by Django 3.2.5 on 2023-04-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0012_alter_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='Activity',
            field=models.CharField(max_length=100),
        ),
    ]
