# Generated by Django 3.2.5 on 2023-05-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0014_resume_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
